build:
  image: docker:25.0.3
  stage: build
  tags:
    - docker
  services:
    - docker:25.0.3-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t c2n-cnit/nfvcl-vnf-manager:latest .
#    - docker push $CI_REGISTRY/c2n-cnit/nfvcl-vnf-manager:latest
